### ISSUE TITLE
underlineColor transparent not working on API 21

### ISSUE THREAD

**Issue by fabOnReact** [fabriziobertoglio1987/react-native-notes#4]
https://github.com/facebook/react-native/pull/30897

The pr fixes issue with `setColorFilter` not working on API 21 by using `setBorderColor` to over-ride it.

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L641-L642

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/Libraries/Components/TextInput/TextInput.js#L906-L911

**Comment by fabOnReact** [comment]
The ReactEditText background image is built with ReactViewBackgroundDrawable

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L130

When we change the TextInput background with `setBorderColor`

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java#L57-L59

The TextInput background Drawable is either retrieved or created:

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java#L27-L43

The class is built on top of the [Drawable Android API](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/graphics/java/android/graphics/drawable/Drawable.java).

Draws the borders using `drawPath`.

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L130-L137

Mutating its borders caused several issues in the past 

https://github.com/facebook/react-native/pull/12493
https://issuetracker.google.com/issues/37068452

```
1. Create a custom Drawable implementation that doesn't override getConstantState().
2. Create a LayerDrawable instance, with an instance of the custom drawable as child.
3. Call mutate() on the LayerDrawable.

- What happened.

The LayerDrawable throws a NullPointerException while trying to create a new instance of the original Drawable from it's non-existent constant state.

java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
    at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1723)
    at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1792)
    at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:152)
    at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1652)
```
https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L217

https://github.com/fabriziobertoglio1987/react-native-notes/blob/573ac3345e77ab472978612ce83d4aabc0ccba99/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L130

https://github.com/aosp-mirror/platform_frameworks_base/blob/1ac46f932ef88a8f96d652580d8105e361ffc842/graphics/java/android/graphics/drawable/Drawable.java#L625
